### ISSUE TITLE
using map in Pluto notebooks

### ISSUE THREAD

**Issue by josephsmann** [davibarreira/Vizagrams.jl#39]
In Pluto notebooks, I get the following error:

Executing
``map(_->Circle(), 1:3)`` 
returns the error message:
> UndefVarError: `Circle` not defined 

the same happens with ``mapreduce`` but not with ``reduce``
eg.
``reduce(→,[Circle(),Circle()])``
works fine.

I am new to Julia so I hope I'm not wasting your time.

**Comment by davibarreira** [comment]
Do you mind sharing more of your Pluto notebook? It looks like Vizagrams was not imported.

**Comment by josephsmann** [comment]
Gladly. here is a [gist link](https://gist.github.com/josephsmann/c630bd40bd26010a1acb49bc8047d2a3)

But I did have `using Vizigrams` and I did make the initial examples work. There's something different about ``map`` but I am too new to Julia to know much more.

and, thanks for this very cool project.

**Comment by josephsmann** [comment]
I could not reproduce this error on Juliahub. Think it's best to ignore unless you can reproduce the behaviour.
I hope no time was wasted on this.
