### ISSUE TITLE
Adding Gadfly restricting Vizagrams version 

### ISSUE THREAD

**Issue by rcqls** [davibarreira/Vizagrams.jl#43]
Hi again,  I was surprised to have my Vizagrams version restricted to v0.1.0

Removing Gadfly saved the issue because Gadfly restricts (indirectly) StatsBase to be at version v0.33 and not v0.34 as in Vizagrams. 

The following output dhow how adding Gadfly downgrade the Vizagrams version. 

```{bash}
(@v1.10) pkg> add Gadfly
   Resolving package versions...
    Updating `~/.julia/environments/v1.10/Project.toml`
  [c91e804a] + Gadfly v1.4.0
⌃ [8c229dad] ↓ Vizagrams v0.2.4 ⇒ v0.1.0
    Updating `~/.julia/environments/v1.10/Manifest.toml`
  [a81c6b42] + Compose v0.9.5
⌅ [7ad07ef1] + CoupledFields v0.2.0
  [c91e804a] + Gadfly v1.4.0
  [a1b4810d] + Hexagons v0.2.0
  [e5e0dc1b] + Juno v0.8.4
  [4345ca2d] + Loess v0.6.4
  [e89f7d12] + Media v0.5.0
⌅ [2913bbd2] ↓ StatsBase v0.34.3 ⇒ v0.33.21
⌃ [8c229dad] ↓ Vizagrams v0.2.4 ⇒ v0.1.0
```

**Comment by davibarreira** [comment]
I think I can downgrade the StatsBase version in the package. This might solve the issue.

**Comment by rcqls** [comment]
> I think I can downgrade the StatsBase version in the package. This might solve the issue.

Yep, I had this in mind, but it is weird that a package restricts the version of statsbase. BTW, I can't see the package in the dependencies of Gadfly that restricts StatsBase to the version v0.33...

**Comment by davibarreira** [comment]
I've downgraded the version deps for StatsBase. I think similar things can be done for other packages if similar issues appear. When defining the dependencies, I just used the latest versions at the time of coding.
Gadfly must use some other package that depends on StatsBase 0.33, that is probably why it implicitly requires 0.33.

**Comment by rcqls** [comment]
Excellent it works!

**Comment by rcqls** [comment]
Excellent it works!
