### ISSUE TITLE
savefig + Line + Mac OS

### ISSUE THREAD

**Issue by jverzani** [davibarreira/Vizagrams.jl#57]
Still very much appreciating the efforts you put into this package. Right now, I am finding an issue saving files with a `Line` object. The following makes a png file as expected:

```
using Vizagrams
a,b,c = [0,0], [1,0], [0,1]
p =  S(:fill=>:red, :opacity=>0.25) * Polygon([a,b,c])
l = S(:strokeWidth=>2)Line([a,b])
savefig(p; filename=expanduser("/tmp/test.png"))
```

But adding in a line results in an all black image. If I add other lines, that image gets clipped so it is related to the l.

```
savefig(p + l; filename="/tmp/test.png")
```

![test](https://github.com/user-attachments/assets/e228874a-e93a-4482-a545-360260cf5259)

(This all came up when trying to use the typst output of quarto which saves files presumably through `savesvg`, there an error ` failed to parse SVG (missing root node)` is thrown, though using the html output this does not occur.)

**Comment by davibarreira** [comment]
> Still very much appreciating the efforts you put into this package. Right now, I am finding an issue saving files with a `Line` object. The following makes a png file as expected:
> 
> 
> 
> ```
> 
> using Vizagrams
> 
> a,b,c = [0,0], [1,0], [0,1]
> 
> p =  S(:fill=>:red, :opacity=>0.25) * Polygon([a,b,c])
> 
> l = S(:strokeWidth=>2)Line([a,b])
> 
> savefig(p; filename=expanduser("/tmp/test.png"))
> 
> ```
> 
> 
> 
> But adding in a line results in an all black image. If I add other lines, that image gets clipped so it is related to the l.
> 
> 
> 
> ```
> 
> savefig(p + l; filename="/tmp/test.png")
> 
> ```
> 
> 
> 
> ![test](https://github.com/user-attachments/assets/e228874a-e93a-4482-a545-360260cf5259)
> 
> 
> 
> 
> 
> (This all came up when trying to use the typst output of quarto which saves files presumably through `savesvg`, there an error ` failed to parse SVG (missing root node)` is thrown, though using the html output this does not occur.)

I'm out the weekend. I'll check on monday. But my guess is that the issue is an svg thing related to line widths and how they scale. Your image is probably black because the line width.

**Comment by jverzani** [comment]
Thanks! You were right. I have to remember the units are not what I expect them to be.

**Comment by davibarreira** [comment]
It is a very annoying issue. I'm working on some variations for the savefig in order to try to avoid this discrepancy between what you see and when you save.
